### PR TITLE
Issue#123

### PR DESCRIPTION
**Pull request by Harold2017**
Add a simple timezone selection field to date form

### CODE REVIEW

**Comment by Harold2017** [comment]
issue #123

**Comment by FlyingBird95** [comment]
Hi Harold,

thank you for implementing this feature. I think that it can be really useful for the Dashboard.

However, I want you to implement the following changes before I'll accept this PR:
- Add the text 'Timezone' after the Clock-icon and change the width of every column to 'col-sm-3' (including the submit-button). Then it will be on a single row. (See the figure below for what I mean)
screen shot 2018-05-09 at 10 02 42
- Set the default value to the users timezone. You can use this Stackoverflow post as an example: https://stackoverflow.com/a/17365806/9752077
- Store the users choice in the database (create a table for this in database/__init__.py). Then, the user doesn't have to change its timezone on every reload.

I'm looking forward to see more contributions from you ;)

Patrick

**Comment by Harold2017** [comment]
Hi Patrick,

Thanks for your reply!
I added this timezone selection on client side but not the server side for the reason that i and my server are not in the same country XD 
I thought i should use the browser's timezone info like `new Date().getTimezoneOffset()`, but i have no idea about how to auto fill the selection form by this acquired default value in a simple way.
I will try to follow your instruction to implement server side first.
Really thank you!~

Harold

**Comment by mircealungu** [comment]
the user's choice could also be stored in a cookie on the browser side... maybe less changes to the DB for this?

**Comment by Harold2017** [comment]
Hi, @mircealungu 
Thanks and i will try it later~

**Pull request closed without merging**
