### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by mircealungu**
folks, is it only me or this line is required for actually reading the configuration file?

### CODE REVIEW

**Comment by mircealungu** [comment]
@bogdanp05 thanks for pulling.
is it possible that the pypi version still has the bug?

**Comment by bogdanp05** [comment]
@mircealungu yes. The pypi version isn't the most recent commit on the master branch, but the one marked as a release. I'm planning to release v2.1.1 this afternoon, which will include both your bug fixes and my recent work, so the pypi version won't have the bug then.

**Comment by mircealungu** [comment]
oki, cool. thanks!

**Comment by bogdanp05** [comment]
@mircealungu The pypi version is now 2.1.1 and contains all the bug fixes

**Comment by mircealungu** [comment]
Nice! Thanks for the heads up!

**Comment by mircealungu** [comment]
I don't remember... Is the big that was making the tests freeze also fixed?

**Comment by bogdanp05** [comment]
@mircealungu I don't think we did that. Are your tests freezing now?

**Comment by mircealungu** [comment]
funny, they seem to not be freezing anymore :)
so you fixed even more than you thought you would
it seems!

**Pull request merged**
