### PR TITLE
Added leading slash to blueprint paths.

### PR DESCRIPTION
**Pull request by XeniaLu**
The wrong rule paths are as follows:

image

### CODE REVIEW

**Comment by bogdanp05** [comment]
Hi @XeniaLu,

What tool are you using to generate the list of paths?  The paths that appear broken in your list work fine for me, e.g. `http://localhost:5000/dashboard/api/versions/1` or `http://localhost:5000/dashboard/api/num_outliers/1`.

Regards,
Bogdan

**Comment by XeniaLu** [comment]
Hello @bogdanp05 ,

I generated the route list by Flask-DebugToolbar. I also tried to access some broken paths, e.g. http://localhost:5000/dashboard/api/deploy_config, it served by the index route and I got the HTML response.

```python
@blueprint.route('/', defaults={'path': ''})
@blueprint.route('/<path:path>')  # Catch-All URL: http://flask.pocoo.org/snippets/57/
@secure
def index(path):
    return render_template('fmd_base.html')
```

But It works for me if I add the leading slash to API paths. For your information, here is the package version I am using:

```
Flask==0.12.2
Flask-MonitoringDashboard==2.1.4
Werkzeug==0.15.2
```

**Comment by bogdanp05** [comment]
>  I also tried to access some broken paths, e.g. http://localhost:5000/dashboard/api/deploy_config

The path [http://localhost:5000/dashboard/api/deploy_config](http://localhost:5000/dashboard/api/deploy_config) wasn't one of the broken ones in your screenshot. Did the links that looked broken in your screenshot (for instance the ones from my previous comment) work for you?

> But It works for me if I add the leading slash to API paths

But did the Flask Monitoring Dashboard throw any errors without the leading slash? Or was it just that `Flask-DebugToolbar` showed some of the paths to be broken?

**Comment by XeniaLu** [comment]
Sorry, my English is bad. 😢 

I mean I cannot get correct JSON response if I call http://localhost:5000/dashboard/api/deploy_config, this URL will redirect me to the `Overview` page. 

If I call http://localhost:5000/dashboardapi/deploy_config, the response is what I need. 

So I did these changes in PR, after add leading slash to deploy_config like that https://github.com/flask-dashboard/Flask-MonitoringDashboard/pull/235/commits/b3704077fe32b729e04d762b6698045fd249f12d#diff-71c9149d18c70363f7dd4c6539f2b427L26, I can get JSON resp from http://localhost:5000/dashboard/api/deploy_config

**Comment by bogdanp05** [comment]
I see the problem, even though I couldn't reproduce it. Since your changes don't break anything and help you access the API, I'll merge the PR.

Thanks for your contribution to the FMD and feel free to do more PRs in the future!
If you like the FMD, it would help us a lot if you could fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)

Regards,
Bogdan

**Pull request merged**
