### PR TITLE
Added sort button in profiler to sort by duration

### PR DESCRIPTION
**Pull request by jangster3794**
Added sort button in profiler to sort by duration

- Added sort button and made necessary changes regarding this for the frontend and Request database class setting index=True by default on these sort keys for faster database queries

### CODE REVIEW

**Comment by mircealungu** [comment]
Dear Rohan,

Does it look like this for you too?
image

I'm not sure why Sort By: is styled like a button. It shouldn't be one.

I think something like this would be a better use of the space:

image

Do you agree? Can you change the layout accordingly? Thanks!

**Comment by jangster3794** [comment]
Hi Mircea,

Thanks for taking the time to review my Pull request.
Sure, I would definitely do that.

I am also going to raise another PR, that will include the sort button
changes and also showing all the headers or parameters if present.
A user can set that value(enable_param_logging) to true or false, And if
set to True, We will display the query arguments and parameters at the top
of the screen.

Attaching a screenshot below,

Please ignore the text inside headers, It is very unclean. I am not sure
how I can beautify that, I am still trying to figure it out.

Any suggestions would be appreciated.

[image: image.png]

**Comment by mircealungu** [comment]
Hi Rohan!

There is no image in your message. 

Also, please consider having two different PRs for the 
two features. Thus, I'd encourage you to finalize the 
sort button in this PR, and open another one for the
other idea. 

Finally, I don't know if you know, but any new commits you
make to the `jangster3794:add-rohan-jangotra` branch
will be added to this PR, so simply make another commit 
with the new style!

Cheers,
M.

**Comment by jangster3794** [comment]
Hi Mircea and FlyingBird95,

I am closing this PR. All of the changes from this PR are already there in the other PR.

Some of the updates related to this have been made on the other branch, i.e. this PR is a little behind the other one.

**Pull request closed without merging**
